/* Main.c file generated by New Project wizard
 *
 * Created:   Thu Jun 26 2025
 * Processor: PIC18F4550
 * Compiler:  MPLAB XC8
 */

#define _XTAL_FREQ 20000000
#include <xc.h>

void main(void)
{
  TRISBbits.TRISB0=0x00;
  while(1)
  {
  TRISBbits.TRISB0 = 1 ;
  __delay_ms(500);
  TRISBbits.TRISB0 = 0 ;
  __delay_ms(500);

}
return;
}
